# SPDX-FileCopyrightText: 2020-2021 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2020-2021 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Habitat-ROS node settings
habitat:
    # Sensor settings
    width: 800
    height: 800
    near_plane: 0.1
    far_plane: 20.0
    f: 400.0
    fps: 30
    enable_semantics: false
    depth_noise: false
    allowed_classes: []

    # Scene settings
    scene_file: "/root/mp3d/gibson/Eastville.glb"
    #scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/1LXtFkjw3qL/1LXtFkjw3qL.glb"
    #scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/2t7WUuJeko7/2t7WUuJeko7.glb"
    #scene_file: "~/Documents/Datasets/Replica/office_0/habitat/mesh_semantic.ply"
    #scene_file: "~/Documents/Datasets/Replica/room_0/habitat/mesh_semantic.ply"

    # Cantwell
    # -7.845426 , 0.1582519, -1.5002776, 0, 2.45858027483337e-05, 0, 1
    # Eastville
    # -0.04129963,  0.17767687, -0.93075943, 0, 2.45858027483337e-05, 0, 1

    initial_T_IC: [ 
        -0.04129963,  0.17767687, -0.93075943, 0, 2.45858027483337e-05, 0, 1
    ]
    pose_frame_id: "habitat"
    pose_frame_at_initial_T_HB: false

    # Visualization settings
    visualize_semantics: false

    # Recording settings
    recording_dir: ""

