# SPDX-FileCopyrightText: 2020-2021 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2020-2021 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Habitat-ROS node settings
habitat:
    # Sensor settings
    width: 800
    height: 800
    near_plane: 0.1
    far_plane: 20.0
    f: 400.0
    fps: 30
    enable_semantics: false
    depth_noise: false
    allowed_classes: []

    # Scene settings
    scene_file: "/root/mp3d/gibson/Elmira.glb"
    #scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/1LXtFkjw3qL/1LXtFkjw3qL.glb"
    #scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/2t7WUuJeko7/2t7WUuJeko7.glb"
    #scene_file: "~/Documents/Datasets/Replica/office_0/habitat/mesh_semantic.ply"
    #scene_file: "~/Documents/Datasets/Replica/room_0/habitat/mesh_semantic.ply"

    initial_T_HB: [ 
        -4.91716055e-05, -9.99999999e-01,  3.14010771e-16,  3.12345893e-01, 9.99999999e-01, -4.91716055e-05,  3.14026212e-16,  6.03794300e+00,-3.14010771e-16,  3.14026212e-16,  1.00000000e+00, -8.29142928e-02, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00,    
    ]
    pose_frame_id: "habitat"
    pose_frame_at_initial_T_HB: false

    # Visualization settings
    visualize_semantics: false

    # Recording settings
    recording_dir: ""

